### ISSUE TITLE
I activated Email Steam guard and this is error is coming now when I try to start it 

### ISSUE THREAD

**Issue by 0xColin** [3urobeat/steam-mass-comment-bot#13]
![image](https://github.com/HerrEurobeat/steam-mass-comment-bot/assets/107142199/1bca9a6d-e9ca-4d5b-8909-a32ea14d6042)

**Comment by 0xColin** [comment]
![image](https://github.com/HerrEurobeat/steam-mass-comment-bot/assets/107142199/8123462a-3217-4ba1-82fb-41686ce32fa6)

This is what it said in output, but it doesn't comment

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
Did you add E-Mail Steam Guard before or after using the bot for the first time?  
In both cases it might be that your login token is invalid for some reason. Please open the `tokens.db` file in the `src` folder with a text editor and delete everything inside. Save and start the bot again. This will prompt you to type in your Steam Guard Code again.  
Please let me know if the bot can log in now.  
  
I should maybe add something that automatically deletes the login token when logging in fails with this error.

**Comment by 0xColin** [comment]
I reinstalled it, and now it's working but one more question how can I post a whole text in a group I put a whole text in "comments.txt" but it's only sending random words.

**Comment by 0xColin** [comment]
bump

**Comment by HerrEurobeat** [comment]
Sorry for not responding sooner, I was on vacation.  
Good to hear the login issue is solved. I just realized the README is indeed missing a proper explanation about the `comments.txt` file, sorry about that.  
The bot chooses a random line from the file for each comment. If you want to post multi-line comments you must separate the lines using the newline escape code `\n`, while being on the same line.  My comment service bot has a better explanation: [click on "Custom quotes (optional)" to expand](https://github.com/HerrEurobeat/steam-comment-service-bot#config-)  
If you always want to send the same message then only provide one line in `comments.txt`, easy.

**Comment by 3urobeat** [comment]
Closing as stale
