### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zRysty** [3urobeat/steam-mass-comment-bot#15]
[output.txt](https://github.com/3urobeat/steam-mass-comment-bot/files/12620741/output.txt)

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue.  
What am I supposed to see in the output.txt file you attached?  
Have you set the profiles & groups you want to comment in in the config.json?

**Comment by 3urobeat** [comment]
Closing as stale
