### ISSUE TITLE
Add support for handling family view

### ISSUE THREAD

**Issue by ultninjaF** [3urobeat/steam-mass-comment-bot#20]
[output.txt](https://github.com/3urobeat/steam-mass-comment-bot/files/15370394/output.txt)
![WindowsTerminal_jDiJxpOq1R](https://github.com/3urobeat/steam-mass-comment-bot/assets/159513745/24b3b3aa-fe5e-4a71-9aa1-614c976917a0)

**Comment by ultninjaF** [comment]
Hello?

**Comment by 3urobeat** [comment]
Hey, sorry, I am busy with other projects and have not found time to try and replicate this issue.  

A HTTP 403 error means Forbidden, aka Steam rejected the request because you aren't allowed to comment.  
Can you comment with that account on that profile manually?  

If yes, then this might be caused by an outdated library the project uses (which I haven't updated in some time).  
If no, then this is account related (although Steam usually returns text errors and not HTTP errors).

**Comment by ultninjaF** [comment]
Yes, manually I can comment on that links I want to. So I need wait an upgrade the project by you?

**Comment by 3urobeat** [comment]
I guess so. I'll check it out in a moment, hopefully I can reproduce the issue.

**Comment by 3urobeat** [comment]
I sadly cannot reproduce the error. Commenting works fine for my (limited) test account, commenting on a profile of a friend.  
I'm going to update the dependencies anyway, maybe that helps.  
I'm not exactly sure what issue you might be running into.

**Comment by ultninjaF** [comment]
Where I can get updated version?

**Comment by 3urobeat** [comment]
From this repo, just download the project again.  
You can copy over `package.json` & `package-lock.json` to your existing installation and run `npm install` again, those are the only two files that have changed.

**Comment by ultninjaF** [comment]
Nothing has been changed T.T
I will wait you to fix the bug, if it will can be

**Comment by 3urobeat** [comment]
Can you try deleting the `tokens.db` file, located in the `src` folder?  
When starting, the bot will ask for your Steam Guard Code again. Maybe the session is invalid or something related to that (although the login should fail altogether if that would be the case)

**Comment by ultninjaF** [comment]
I've found what the issue is. Bot cannot avoid family view. Started to work when I turned it off. Can you add plugin that can work with family view?

**Comment by ultninjaF** [comment]
At least add something like login secure where need to write family view token from cookies

**Comment by 3urobeat** [comment]
Oh, that's interesting! I have not yet worked with any of the family related features of Steam at all.  
I have to see if/how I can interact with family view from the steam-user library

**Comment by 3urobeat** [comment]
Version 2.3.0 is now out which adds support for this feature.
