### ISSUE TITLE
Comment destiantion

### ISSUE THREAD

**Issue by maldeholm** [3urobeat/steam-mass-comment-bot#22]
Hi 
I tried to use it but every time it says  ERROR] No destinations set in config to comment on! Exiting...
hope you can help

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue!  

Could you send the content of your `config.json` file?  
The error message states that you didn't set any destinations where to comment at in the config.

**Comment by maldeholm** [comment]
Hi I will send it one of the next days:)
