### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ultninjaF** [3urobeat/steam-mass-comment-bot#24]
Hi. I have some troubles. I've updated the version and now it doesn't work...
![WindowsTerminal_X3S4RLW1eK](https://github.com/user-attachments/assets/01c247d1-a052-4b19-adab-c17a641026ef)

**Comment by ultninjaF** [comment]
![Uploading ApplicationFrameHost_llqUarH02v.png…]()

**Comment by ultninjaF** [comment]
![ApplicationFrameHost_llqUarH02v](https://github.com/user-attachments/assets/1546baf3-eca7-43f3-b0b8-a996a1b08f53)

**Comment by ultninjaF** [comment]
[output.txt](https://github.com/user-attachments/files/17695613/output.txt)

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue!

Your destinations file is formatted wrong. Only put the URL itself on one line, no quotation marks, no commas, no extra spaces.  

The quotation marks and commas were only necessary for the JSON formatted config file, this is a raw text file now.

**Comment by ultninjaF** [comment]
Thx for the answer. I've fixed it. You should change the instruction. It's for the old version.  "Destinations" chapter.

**Comment by 3urobeat** [comment]
Whoops, sorry, I updated the description but forgot to update the example.  
Thanks for letting me know. Fixed now.
